
//All available modbus registers. 
#define MB_BIT_INPUT_OCP_ADDR_START			1000 // Done

// Bit access -	Internal Bits or Physical Coils:
//					Function: Read Coils (01)
#define MB_BIT_INPUT_RLY_ADDR_START			2000 // Done
#define MB_BIT_INPUT_STATUS_ADDR_START		2100		// SYS, REC, SM // Done
//#define MB_BIT_INPUT_SYS_ADDR_START			2100
//#define MB_BIT_INPUT_REC_ADDR_START			2108
//#define MB_BIT_INPUT_SM_ADDR_START			2016
#define MB_BIT_INPUT_RST_ADDR_START			2200 // Done
//					Function: Write Single Coil (05)
//					Function: Write Multiple Coils (15)
#define MB_BIT_OUTPUT_RLY_ADDR_START		2000
#define MB_BIT_OUTPUT_SYS_ADDR_START		2100
#define MB_BIT_OUTPUT_REC_ADDR_START		2108

// 16-Bits access -	Physical Input Registers:
//					Function: Read Input Register(s) (04)
#define MB_REG_INPUT_ADC_ADDR_START			3000 // Done

// 16-Bits access -	Internal Registers or Physical Output Registers:
//					Function: Read Holding Register(s) (03)
#define MB_REG_INPUT_CALIB_ADDR_START		4000 //Done
#define MB_REG_INPUT_HW_FW_ADDR_START		4100 //Done
#define MB_REG_INPUT_MODE_ADDR_START		4200 // Done
#define MB_REG_INPUT_DDS_ADDR_START			4300 // Done
#define MB_REG_INPUT_ITRIP_ADDR_START		4400 //Done 
#define MB_REG_INPUT_DPLL_ADDR_START		4500 //Done 
//#define MB_REG_INPUT_SM_ADDR_START			9000 //Debug Purpose Only doesn´t added here
//#define MB_REG_INPUT_REC_INFO_ADDR_START	9100 // Debug Purpose Only doesn´t added here
//#define MB_REG_INPUT_REC_DATA_ADDR_START	9200 // Debug Purpose Only doesn´t added here
//					Function: Write Single Register (06)
//					Function: Write Multiple Registers (16)
#define MB_REG_OUTPUT_MODE_ADDR_START		4202	// Skip UpTime
#define MB_REG_OUTPUT_DDS_ADDR_START		4300
#define MB_REG_OUTPUT_ITRIP_ADDR_START		4400
#define MB_REG_OUTPUT_DPLL_ADDR_START		4500



/***********************************Read Discrete Inputs Adress:1000 ****************************************************************************************************/
MODBUS_GROUP(MB_BIT_INPUT_OCP_ADDR_START,Read_Discrete_Inputs)			//Read_OCP_Detector inputs states
        
MODBUS_DATA	(MB_BIT_INPUT_OCP_ADDR_START,	OCP_OC_L1_INV,	BOOL,Discrete_Inputs.OCP_OC_L1_INV)	//L1_INV input state of OCP Detector
MODBUS_DATA	(MB_BIT_INPUT_OCP_ADDR_START+1,	OCP_OC_L2_INV,	BOOL,Discrete_Inputs.OCP_OC_L2_INV)	//L2_INV input state of OCP Detector
MODBUS_DATA	(MB_BIT_INPUT_OCP_ADDR_START+2,	OCP_OC_L3_INV,	BOOL,Discrete_Inputs.OCP_OC_L3_INV)	//L3_INV input state of OCP Detector
MODBUS_DATA	(MB_BIT_INPUT_OCP_ADDR_START+3,	OCP_OC_L1_GRID,	BOOL,Discrete_Inputs.OCP_OC_L1_GRID)	//L1_GRID input state of OCP Detector
MODBUS_DATA	(MB_BIT_INPUT_OCP_ADDR_START+4,	OCP_OC_L2_GRID,	BOOL,Discrete_Inputs.OCP_OC_L2_GRID)	//L2_GRID input state of OCP Detector
MODBUS_DATA	(MB_BIT_INPUT_OCP_ADDR_START+5,	OCP_OC_L3_GRID,	BOOL,Discrete_Inputs.OCP_OC_L3_GRID)	//L3_GRID input state of OCP Detector
        
/***********************************RLY outputs states, RST sources & system STATUS Adress 2000 *************************************************************************************************/
 
MODBUS_GROUP(MB_BIT_INPUT_RLY_ADDR_START,	RLY_OUTPUT_STATES)			
MODBUS_DATA	(MB_BIT_INPUT_RLY_ADDR_START,       RELAY_INV_PHASE,	BOOL,	Relay_Output.RELAY_INV_PHASE)	//INV_PHASE relay output state)
MODBUS_DATA	(MB_BIT_INPUT_RLY_ADDR_START+1,     RELAY_INV_NEUTRAL,	BOOL,	Relay_Output.RELAY_INV_NEUTRAL)	//INV_NEUTRAL relay output state)
MODBUS_DATA	(MB_BIT_INPUT_RLY_ADDR_START+2,     RELAY_GRID_PHASE,	BOOL,	Relay_Output.RELAY_GRID_PHASE)	//GRID_PHASE relay output state)
MODBUS_DATA	(MB_BIT_INPUT_RLY_ADDR_START+3,     RELAY_GRID_NEUTRAL,	BOOL,	Relay_Output.RELAY_GRID_NEUTRAL)	//GRID_NEUTRAL relay output state)

/*********************************** Read system STATUS SYS, REC & SM Adress 2100*************************************************************************************************/     
       
MODBUS_GROUP(MB_BIT_INPUT_STATUS_ADDR_START,	System_Status_REC_SYS_SM)						
MODBUS_DATA	(MB_BIT_INPUT_STATUS_ADDR_START,	SYS_RELOADED,       BOOL,	System_Status.SYS_RELOADED)     //	SYS_RELOADED flag state	
MODBUS_DATA	(MB_BIT_INPUT_STATUS_ADDR_START	+1,	SYS_SHUTDOWN,       BOOL,	System_Status.SYS_SHUTDOWN)         //	SYS_SHUTDOWN flag state	
MODBUS_DATA	(MB_BIT_INPUT_STATUS_ADDR_START	+8,	REC_DATA_READY,     BOOL,	System_Status.REC_DATA_READY)       //	REC_DATA_READY flag state	for debug only
MODBUS_DATA	(MB_BIT_INPUT_STATUS_ADDR_START	+9,	REC_DATA_REREAD,    BOOL,	System_Status.REC_DATA_REREAD)	//	REC_DATA_REREAD flag state	for debug only
MODBUS_DATA	(MB_BIT_INPUT_STATUS_ADDR_START	+16,	SM_REC_STATE,       BOOL,	System_Status.SM_REC_STATE)         //	SM_REC_STATE flag state	for debug only

        
/***********************************        Read RST sources Address 2200*************************************************************************************************/
MODBUS_GROUP	(	MB_BIT_INPUT_RST_ADDR_START, RST_SOURCES)									//	
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START,		RST_POR	,	BOOL,	Reset_Source.RST_POR	)	//	RST_POR flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+1,     RST_BOR,	BOOL,	Reset_Source.RST_BOR	)	//	RST_BOR flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+2,     RST_IDLE,	BOOL,	Reset_Source.RST_IDLE	)	//	RST_IDLE flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+3,     RST_SLEEP,	BOOL,	Reset_Source.RST_SLEEP	)	//	RST_SLEEP flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+4,     RST_WDTO,	BOOL,	Reset_Source.RST_WDTO	)	//	RST_WDTO flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+5,     RST_SWDTEN,	BOOL,	Reset_Source.RST_SWDTEN	)	//	RST_SWDTEN flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+6,     RST_SWR,	BOOL,	Reset_Source.RST_SWR	)	//	RST_SWR flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+7,     RST_EXTR,	BOOL,	Reset_Source.RST_EXTR	)	//	RST_EXTR flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+8,     RST_VREGS,	BOOL,	Reset_Source.RST_VREGS	)	//	RST_VREGS flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+9,     RST_CM,     BOOL,	Reset_Source.RST_CM     )	//	RST_CM flag state
//MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+10,	DummyOnAdress10,	BOOL,       Reset_Source.DummyOnAddress10	)
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+11,	RST_VREGSF,	BOOL,	Reset_Source.RST_VREGSF	)	//	RST_VREGSF flag state
//MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+12,	DummyOnAddress12,	BOOL,	Reset_Source.DummyOnAddress12	)
//MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+13,	DummyOnAddress13,	BOOL,	Reset_Source.DummyOnAddress13	)
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+14,	RST_IOPUWR,	BOOL,	Reset_Source.RST_IOPUWR	)	//	RST_IOPUWR flag state
MODBUS_DATA	(	MB_BIT_INPUT_RST_ADDR_START	+15,	RST_TRAPR,	BOOL,	Reset_Source.RST_TRAPR	)	//	RST_TRAPR flag state
        
/***********************************ADC Reading Adress: 3000 *************************************************************************************************/
       
MODBUS_GROUP	(	MB_REG_INPUT_ADC_ADDR_START ,	ADC_READING)		
        	
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START     ,	L1_U_INV_RAW,	UINT16_TO_UINT16,	Adc_Reading.L1_U_INV_RAW	)	//	L1_U_INV value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+1	,	L1_U_INV_MEAN,	INT16_TO_INT16	,	Adc_Reading.L1_U_INV_MEAN	)	//	L1_U_INV mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+2	,	L1_U_INV_PKPK,	INT16_TO_INT16	,	Adc_Reading.L1_U_INV_PKPK	)	//	L1_U_INV pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+3	,	L1_U_INV_RMS,	INT16_TO_INT16	,	Adc_Reading.L1_U_INV_RMS	)	//	L1_U_INV RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+4	,	L1_I_INV_RAW,	UINT16_TO_UINT16,	Adc_Reading.L1_I_INV_RAW	)	//	L1_I_INV value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+5	,	L1_I_INV_MEAN,	INT16_TO_INT16	,	Adc_Reading.L1_I_INV_MEAN	)	//	L1_I_INV mean value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+6	,	L1_I_INV_PKPK,	INT16_TO_INT16	,	Adc_Reading.L1_I_INV_PKPK	)	//	L1_I_INV pk-pk value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+7	,	L1_I_INV_RMS,	INT16_TO_INT16	,	Adc_Reading.L1_I_INV_RMS	)	//	L1_I_INV RMS value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+8	,	L2_U_INV_RAW,	UINT16_TO_UINT16,	Adc_Reading.L2_U_INV_RAW	)	//	L2_U_INV value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+9	,	L2_U_INV_MEAN,	INT16_TO_INT16	,	Adc_Reading.L2_U_INV_MEAN	)	//	L2_U_INV mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+10	,	L2_U_INV_PKPK,	INT16_TO_INT16	,	Adc_Reading.L2_U_INV_PKPK	)	//	L2_U_INV pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+11	,	L2_U_INV_RMS,	INT16_TO_INT16	,	Adc_Reading.L2_U_INV_RMS	)	//	L2_U_INV RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+12	,	L2_I_INV_RAW,	UINT16_TO_UINT16,	Adc_Reading.L2_I_INV_RAW	)	//	L2_I_INV value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+13	,	L2_I_INV_MEAN,	INT16_TO_INT16	,	Adc_Reading.L2_I_INV_MEAN	)	//	L2_I_INV mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+14	,	L2_I_INV_PKPK,	INT16_TO_INT16	,	Adc_Reading.L2_I_INV_PKPK	)	//	L2_I_INV pk-pk value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+15	,	L2_I_INV_RMS,	INT16_TO_INT16	,	Adc_Reading.L2_I_INV_RMS	)	//	L2_I_INV RMS value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+16	,	L3_U_INV_RAW,	UINT16_TO_UINT16,	Adc_Reading.L3_U_INV_RAW	)	//	L3_U_INV value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+17	,	L3_U_INV_MEAN,	INT16_TO_INT16	,	Adc_Reading.L3_U_INV_MEAN	)	//	L3_U_INV mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+18	,	L3_U_INV_PKPK,	INT16_TO_INT16	,	Adc_Reading.L3_U_INV_PKPK	)	//	L3_U_INV pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+19	,	L3_U_INV_RMS,	INT16_TO_INT16	,	Adc_Reading.L3_U_INV_RMS	)	//	L3_U_INV RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+20	,	L3_I_INV_RAW,	UINT16_TO_UINT16,	Adc_Reading.L3_I_INV_RAW	)	//	L3_I_INV value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+21	,	L3_I_INV_MEAN,	INT16_TO_INT16	,	Adc_Reading.L3_I_INV_MEAN	)	//	L1_I_INV mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+22	,	L3_I_INV_PKPK,	INT16_TO_INT16	,	Adc_Reading.L3_I_INV_PKPK	)	//	L1_I_INV pk-pk value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+23	,	L3_I_INV_RMS,	INT16_TO_INT16	,	Adc_Reading.L3_I_INV_RMS	)	//	L1_I_INV RMS value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+24	,	L1_U_MID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L1_U_MID_RAW	)	//	L1_U_MID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+25	,	L1_U_MID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L1_U_MID_MEAN	)	//	L1_U_MID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+26	,	L1_U_MID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L1_U_MID_PKPK	)	//	L1_U_MID pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+27	,	L1_U_MID_RMS,	INT16_TO_INT16	,	Adc_Reading.L1_U_MID_RMS	)	//	L1_U_MID RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+28	,	L2_U_MID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L2_U_MID_RAW	)	//	L2_U_MID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+29	,	L2_U_MID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L2_U_MID_MEAN	)	//	L2_U_MID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+30	,	L2_U_MID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L2_U_MID_PKPK	)	//	L2_U_MID pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+31	,	L2_U_MID_RMS,	INT16_TO_INT16	,	Adc_Reading.L2_U_MID_RMS	)	//	L2_U_MID RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+32	,	L3_U_MID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L3_U_MID_RAW	)	//	L3_U_MID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+33	,	L3_U_MID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L3_U_MID_MEAN	)	//	L3_U_MID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+34	,	L3_U_MID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L3_U_MID_PKPK	)	//	L3_U_MID pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+35	,	L3_U_MID_RMS,	INT16_TO_INT16	,	Adc_Reading.L3_U_MID_RMS	)	//	L3_U_MID RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+36	,	L1_U_GRID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L1_U_GRID_RAW	)	//	L1_U_GRID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+37	,	L1_U_GRID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L1_U_GRID_MEAN	)	//	L1_U_GRID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+38	,	L1_U_GRID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L1_U_GRID_PKPK	)	//	L1_U_GRID pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+39	,	L1_U_GRID_RMS,	INT16_TO_INT16	,	Adc_Reading.L1_U_GRID_RMS	)	//	L1_U_GRID RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+40	,	L1_I_GRID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L1_I_GRID_RAW	)	//	L1_I_GRID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+41	,	L1_I_GRID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L1_I_GRID_MEAN	)	//	L1_I_GRID mean value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+42	,	L1_I_GRID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L1_I_GRID_PKPK	)	//	L1_I_GRID pk-pk value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+43	,	L1_I_GRID_RMS,	INT16_TO_INT16	,	Adc_Reading.L1_I_GRID_RMS	)	//	L1_I_GRID RMS value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+44	,	L2_U_GRID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L2_U_GRID_RAW	)	//	L2_U_GRID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+45	,	L2_U_GRID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L2_U_GRID_MEAN	)	//	L2_U_GRID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+46	,	L2_U_GRID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L2_U_GRID_PKPK	)	//	L2_U_GRID pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+47	,	L2_U_GRID_RMS,	INT16_TO_INT16	,	Adc_Reading.L2_U_GRID_RMS	)	//	L2_U_GRID RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+48	,	L2_I_GRID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L2_I_GRID_RAW	)	//	L2_I_GRID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+49	,	L2_I_GRID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L2_I_GRID_MEAN	)	//	L2_I_GRID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+50	,	L2_I_GRID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L2_I_GRID_PKPK	)	//	L2_I_GRID pk-pk value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+51	,	L2_I_GRID_RMS,	INT16_TO_INT16	,	Adc_Reading.L2_I_GRID_RMS	)	//	L2_I_GRID RMS value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+52	,	L3_U_GRID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L3_U_GRID_RAW	)	//	L3_U_GRID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+53	,	L3_U_GRID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L3_U_GRID_MEAN	)	//	L3_U_GRID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+54	,	L3_U_GRID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L3_U_GRID_PKPK	)	//	L3_U_GRID pk-pk value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+55	,	L3_U_GRID_RMS,	INT16_TO_INT16	,	Adc_Reading.L3_U_GRID_RMS	)	//	L3_U_GRID RMS value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+56	,	L3_I_GRID_RAW,	UINT16_TO_UINT16,	Adc_Reading.L3_I_GRID_RAW	)	//	L3_I_GRID value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+57	,	L3_I_GRID_MEAN,	INT16_TO_INT16	,	Adc_Reading.L3_I_GRID_MEAN	)	//	L1_I_GRID mean value in 1/32 V units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+58	,	L3_I_GRID_PKPK,	INT16_TO_INT16	,	Adc_Reading.L3_I_GRID_PKPK	)	//	L1_I_GRID pk-pk value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+59	,	L3_I_GRID_RMS,	INT16_TO_INT16	,	Adc_Reading.L3_I_GRID_RMS	)	//	L1_I_GRID RMS value in 1/32 A units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+60	,	P_U_DC_RAW,     UINT16_TO_UINT16,	Adc_Reading.P_U_DC_RAW	)	//	P_U_DC_RAW
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+61	,	P_U_DC_MEAN,	UINT16_TO_UINT16,	Adc_Reading.P_U_DC_MEAN	)	//	P_U_DC_MEAN
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+62	,	P_U_DC_PKPK,	UINT16_TO_UINT16,	Adc_Reading.P_U_DC_PKPK	)	//	P_U_DC_PKPK
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+63	,	P_U_DC_RMS,     UINT16_TO_UINT16,	Adc_Reading.P_U_DC_RMS	)	//	P_U_DC_RMS
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+64	,	N_U_DC_RAW,     UINT16_TO_UINT16,	Adc_Reading.N_U_DC_RAW	)	//	N_U_DC_RAW
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+65	,	N_U_DC_MEAN,	UINT16_TO_UINT16,	Adc_Reading.N_U_DC_MEAN	)	//	N_U_DC_MEAN
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+66	,	N_U_DC_PKPK,	UINT16_TO_UINT16,	Adc_Reading.N_U_DC_PKPK	)	//	N_U_DC_PKPK
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+67	,	N_U_DC_RMS,     UINT16_TO_UINT16,	Adc_Reading.N_U_DC_RMS	)	//	N_U_DC_RMS
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+68	,	T1_RAW,         UINT16_TO_UINT16,	Adc_Reading.T1_RAW	)	//	T1_RAW value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+69	,	T1_CELSIUS,     INT16_TO_INT16	,	Adc_Reading.T1_CELSIUS	)	//	T1_CELSIUS value in 1/10 °C units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+70	,	T1_RESISTANCE,	UINT64_TO_UINT64,	Adc_Reading.T1_RESISTANCE,.count =2	)	//	T1_RESISTANCE value in 1/10 ? units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+72	,	T2_RAW,         UINT16_TO_UINT16,	Adc_Reading.T2_RAW	)	//	T2_RAW value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+73	,	T2_CELSIUS,     INT16_TO_INT16	,	Adc_Reading.T2_CELSIUS	)	//	T2_CELSIUS value in 1/10 °C units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+74	,	T2_RESISTANCE,	UINT64_TO_UINT64,	Adc_Reading.T2_RESISTANCE, .count =2	)	//	T2_RESISTANCE value in 1/10 ? units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+76	,	T3_RAW,         UINT16_TO_UINT16,	Adc_Reading.T3_RAW	)	//	T3_RAW value in ADC steps units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+77	,	T3_CELSIUS,     INT16_TO_INT16	,	Adc_Reading.T3_CELSIUS	)	//	T3_CELSIUS value in 1/10 °C units
MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+78	,	T3_RESISTANCE,	UINT64_TO_UINT64,	Adc_Reading.T3_RESISTANCE, .count =2	)	//	T3_RESISTANCE value in 1/10 ? units

//UNUSED        
//MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+75	,		,		,	Adc_Reading.		)	//	      
//MODBUS_DATA	(	MB_REG_INPUT_ADC_ADDR_START	+71	,		,		,	Adc_Reading.		)	//	
        
        
        
         /***********************************Calibration Information Address: 4000 *************************************************************************************************/
       
MODBUS_GROUP(MB_REG_INPUT_CALIB_ADDR_START, CALIB_HW_FW)
        
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START,      L1_I_INV_RAW_ERR,   UINT16_TO_UINT16,   Calib_info.L1_I_INV_RAW_ERR)	//R	INT	L1_I_INV_RAW_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+1,    L1_I_INV_UNIT_ERR,  UINT16_TO_UINT16,   Calib_info.L1_I_INV_UNIT_ERR)	//R	INT	L1_I_INV_ERR value in 1/32 A units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+2,    L2_I_INV_RAW_ERR,   UINT16_TO_UINT16,   Calib_info.L2_I_INV_RAW_ERR)	//R	INT	L2_I_INV_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+3,    L2_I_INV_UNIT_ERR,  UINT16_TO_UINT16,   Calib_info.L2_I_INV_UNIT_ERR)	//R	INT	L2_I_INV_ERR value in 1/32 A units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+4,    L3_I_INV_RAW_ERR,   UINT16_TO_UINT16,   Calib_info.L3_I_INV_RAW_ERR)	//R	INT	L3_I_INV_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+5,    L3_I_INV_UNIT_ERR,  UINT16_TO_UINT16,   Calib_info.L3_I_INV_UNIT_ERR)	//R	INT	L3_I_INV_ERR value in 1/32 A units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+6,    L1_I_GRID_RAW_ERR,  UINT16_TO_UINT16,   Calib_info.L1_I_GRID_RAW_ERR)	//R	INT	L1_I_GRID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+7,    L1_I_GRID_UNIT_ERR, UINT16_TO_UINT16,   Calib_info.L1_I_GRID_UNIT_ERR)	//R	INT	L1_I_GRID_ERR value in 1/32 A units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+8,    L2_I_GRID_RAW_ERR,  UINT16_TO_UINT16,   Calib_info.L2_I_GRID_RAW_ERR)   //R	INT	L2_I_GRID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+9,    L2_I_GRID_UNIT_ERR, UINT16_TO_UINT16,   Calib_info.L2_I_GRID_UNIT_ERR)	//R	INT	L2_I_GRID_ERR value in 1/32 A units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+10,	L3_I_GRID_RAW_ERR,  UINT16_TO_UINT16,   Calib_info.L3_I_GRID_RAW_ERR)	//R	INT	L3_I_GRID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+11,	L3_I_GRID_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L3_I_GRID_UNIT_ERR)	//R	INT	L3_I_GRID_ERR value in 1/32 A units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+12,	L1_U_INV_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L1_U_INV_RAW_ERR)	//R	INT	L1_U_INV_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+13,	L1_U_INV_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L1_U_INV_UNIT_ERR)	//R	INT	L1_U_INV_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+14,	L2_U_INV_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L2_U_INV_RAW_ERR)	//R	INT	L2_U_INV_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+15,	L2_U_INV_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L2_U_INV_UNIT_ERR)	//R	INT	L2_U_INV_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+16,	L3_U_INV_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L3_U_INV_RAW_ERR)	//R	INT	L3_U_INV_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+17,	L3_U_INV_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L3_U_INV_UNIT_ERR)	//R	INT	L3_U_INV_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+18,	L1_U_MID_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L1_U_MID_RAW_ERR)	//R	INT	L1_U_MID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+19,	L1_U_MID_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L1_U_MID_UNIT_ERR)	//R	INT	L1_U_MID_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+20,	L2_U_MID_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L2_U_MID_RAW_ERR)	//R	INT	L2_U_MID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+21,	L2_U_MID_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L2_U_MID_UNIT_ERR)	//R	INT	L2_U_MID_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+22,	L3_U_MID_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L3_U_MID_RAW_ERR)	//R	INT	L3_U_MID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+23,	L3_U_MID_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L3_U_MID_UNIT_ERR)	//R	INT	L3_U_MID_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+24,	L1_U_GRID_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L1_U_GRID_RAW_ERR)	//R	INT	L1_U_GRID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+25,	L1_U_GRID_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L1_U_GRID_UNIT_ERR)	//R	INT	L1_U_GRID_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+26,	L2_U_GRID_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L2_U_GRID_RAW_ERR)	//R	INT	L2_U_GRID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+27,	L2_U_GRID_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L2_U_GRID_UNIT_ERR)	//R	INT	L2_U_GRID_ERR value in 1/32 V units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+28,	L3_U_GRID_RAW_ERR,	UINT16_TO_UINT16,   Calib_info.L3_U_GRID_RAW_ERR)	//R	INT	L3_U_GRID_ERR value in ADC steps units	
MODBUS_DATA(MB_REG_INPUT_CALIB_ADDR_START+29,	L3_U_GRID_UNIT_ERR,	UINT16_TO_UINT16,   Calib_info.L3_U_GRID_UNIT_ERR)	//R	INT	L3_U_GRID_ERR value in 1/32 V units	

/***********************************Hardware Info Adress 4100****************************************************************************************************/

MODBUS_GROUP(MB_REG_INPUT_HW_FW_ADDR_START, HW_SW_INFO)
MODBUS_DATA (MB_REG_INPUT_HW_FW_ADDR_START,   HW_INFO,      UINT16_TO_UINT16, Device_info.HW_INFO)
MODBUS_DATA (MB_REG_INPUT_HW_FW_ADDR_START+1, FW_VERSION,   UINT16_TO_UINT16, Device_info.FW_VERSION)
MODBUS_DATA (MB_REG_INPUT_HW_FW_ADDR_START+2, FW_DATE,      UINT16_TO_UINT16, Device_info.FW_DATE)
MODBUS_DATA (MB_REG_INPUT_HW_FW_ADDR_START+3, FW_MONTH_DAY, UINT16_TO_UINT16, Device_info.FW_MONTH_DAY)
        
        
/***********************************Mode Reading Adress 4200****************************************************************************************************/
MODBUS_GROUP(	MB_REG_INPUT_MODE_ADDR_START, MODE_INFO_READINGS)											//	
MODBUS_DATA	(	MB_REG_INPUT_MODE_ADDR_START,   POWERUP_COUNTER,	UINT64_TO_UINT64,	Mode_Reading.POWERUP_COUNTER,.count =2)	//	Timer ticks since powerup in 1s units
//MODBUS_DATA	(	MB_REG_INPUT_MODE_ADDR_START	+	1	,	 	,					;	//	
MODBUS_DATA	(	MB_REG_INPUT_MODE_ADDR_START+2, SM_SYSTEM_MODE, 	UINT16_TO_UINT16,	Mode_Reading.SYSTEM_MODE)	//	System mode
        
        
        
/***********************************DDS Readings Adress 4300****************************************************************************************************/
        
MODBUS_GROUP(	MB_REG_INPUT_DDS_ADDR_START	,DDS_READINGS)	//	
MODBUS_DATA	(	MB_REG_INPUT_DDS_ADDR_START,	WAVES_FREQ,         UINT16_TO_UINT16,		DDS_Reading.WAVES_FREQ      )	//	Frequency in 1/10 Hz units
MODBUS_DATA	(	MB_REG_INPUT_DDS_ADDR_START	+1,	SHIFT_PHASE_CH2,	INT16_TO_INT16,         DDS_Reading.SHIFT_PHASE_CH2	)	//	Phase shift for CH2 in 1/10 ° DEG
MODBUS_DATA	(	MB_REG_INPUT_DDS_ADDR_START	+2,	SHIFT_PHASE_CH3,	INT16_TO_INT16,         DDS_Reading.SHIFT_PHASE_CH3	)	//	Phase shift for CH3 in 1/10 ° DEG
MODBUS_DATA	(	MB_REG_INPUT_DDS_ADDR_START	+3,	GAIN_CH1,           UINT16_TO_UINT16,		DDS_Reading.GAIN_CH1        )	//	Amplitude for CH1 in range 0->65535
MODBUS_DATA	(	MB_REG_INPUT_DDS_ADDR_START	+4,	GAIN_CH2,           UINT16_TO_UINT16,		DDS_Reading.GAIN_CH2        )	//	Amplitude for CH2 in range 0->65535
MODBUS_DATA	(	MB_REG_INPUT_DDS_ADDR_START	+5,	GAIN_CH3,           UINT16_TO_UINT16,		DDS_Reading.GAIN_CH3        )	//	Amplitude for CH3 in range 0->65535

        
        
/***********************************ITRIP READINGS Adress 4400****************************************************************************************************/
MODBUS_GROUP(   MB_REG_INPUT_ITRIP_ADDR_START, ITRIP_READINGS)	//	
MODBUS_DATA	(   MB_REG_INPUT_ITRIP_ADDR_START,     ITRIP_INV_UPPER,    UINT16_TO_UINT16,       ITRIP_Reading.ITRIP_INV_UPPER     )	//	 ITRIP_INV_UPPER in range 0->65535
MODBUS_DATA	(   MB_REG_INPUT_ITRIP_ADDR_START +1,	ITRIP_GRID_LOWER,   UINT16_TO_UINT16,       ITRIP_Reading.ITRIP_GRID_LOWER    ) //     ITRIP_GRID_LOWER in range 0->65535
        
/***********************************DPLL READINGS Adress 4500****************************************************************************************************/
MODBUS_GROUP(MB_REG_INPUT_DPLL_ADDR_START, DPLL_READINGS)
MODBUS_DATA	(	MB_REG_INPUT_DPLL_ADDR_START,	ID_SET,     INT16_TO_INT16,		DPLL_Reading.ID_SET	 )	//	ID_SET in range -32768 to 32767
MODBUS_DATA	(	MB_REG_INPUT_DPLL_ADDR_START+1,	IQ_SET,     INT16_TO_INT16,		DPLL_Reading.IQ_SET	 ) 	//	IQ_SET in range -32768 to 32767
MODBUS_DATA	(	MB_REG_INPUT_DPLL_ADDR_START+2,	VD_SET,     INT16_TO_INT16,		DPLL_Reading.VD_SET	 )	//	VD_SET in range -32768 to 32767
MODBUS_DATA	(	MB_REG_INPUT_DPLL_ADDR_START+3,	VQ_SET,     INT16_TO_INT16,		DPLL_Reading.VQ_SET	 )	//	VQ_SET in range -32768 to 32767
MODBUS_DATA	(	MB_REG_INPUT_DPLL_ADDR_START+4,	OMEGA_L,	INT16_TO_INT16,		DPLL_Reading.OMEGA_L )	//	OMEGA_L in range -32768 to 32767
        
/*********************************** SM READINGS Adress 9000****************************************************************************************************/       
        
 /*       
MODBUS_GROUP(	MB_REG_INPUT_SM_ADDR_START,	SM_READINGS	)	//	
MODBUS_DATA	(	MB_REG_INPUT_SM_ADDR_START,		SM_REC_STATE,       UINT8_TO_UINT8,      SM_Reading.SM_REC_STATE	)	//	SM State
MODBUS_DATA	(	MB_REG_INPUT_SM_ADDR_START+1,	SM_STATE_ERROR,     UINT16_TO_UINT16,    SM_Reading.SM_STATE_ERROR	)	//	SM ERROR
MODBUS_DATA	(	MB_REG_INPUT_SM_ADDR_START+2,	SM_TIMESTAMP_MS,	UINT16_TO_UINT16,	SM_Reading.SM_TIMESTAMP_MS	)	//	Time in ms
MODBUS_DATA	(	MB_REG_INPUT_SM_ADDR_START+3,	SM_TIMESTAMP_S,     UINT64_TO_UINT64,	SM_Reading.SM_TIMESTAMP_S	)	//	Time in s
*/