/*
 *  File name: config_pwm.h
 *
 *  Description: PWM peripheral settings
 *
 *  Author: Future Electronics
 *
 */

#ifndef CONFIG_PWM_H
#define CONFIG_PWM_H

#include "types_pwm.h"
#include "config_system.h"

//*****************************************************************************
//
// PWM BSP settings.
//
//*****************************************************************************

// Minimum Dead Times for IGBTs and Gate Drivers (Rising Edge & Falling Edge)
#if ((!defined EVAL_BOARD) && (!defined PINS28_STARTER_BOARD))
// Inresol Inverter
#define BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_RISING_EDGE			400		// 400ns
#define BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_FALLING_EDGE		400		// 400ns
#define BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_RISING_EDGE		100		// 100ns
#define BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_FALLING_EDGE	100		// 100ns
#else	// EVAL_BOARD
// Engineering Sample Evaluation Board
// 28-pins Starter Board
#define BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_RISING_EDGE			25		// 25ns
#define BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_FALLING_EDGE		50		// 50ns
#define BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_RISING_EDGE		25		// 25ns
#define BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_FALLING_EDGE	50		// 50ns
#endif	// EVAL_BOARD

//*****************************************************************************
//
// PWM App settings.
//
//*****************************************************************************

// Default Dead Times for IGBTs and Gate Drivers (Rising Edge & Falling Edge)
#if ((!defined EVAL_BOARD) && (!defined PINS28_STARTER_BOARD))
// Inresol Inverter
#if 0
#define APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE			400		// 400ns
#define APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE		400		// 400ns
#define APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_RISING_EDGE		100		// 100ns
#define APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_FALLING_EDGE	100		// 100ns
#else
#define APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE			800		// 800ns
#define APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE		800		// 800ns
#define APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_RISING_EDGE		200		// 200ns
#define APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_FALLING_EDGE	200		// 200ns
#endif
#else	// EVAL_BOARD
// Engineering Sample Evaluation Board
// 28-pins Starter Board
#define APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE			25		// 25ns
#define APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE		50		// 50ns
#define APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_RISING_EDGE		25		// 25ns
#define APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_FALLING_EDGE	50		// 50ns
#endif	// EVAL_BOARD

// Default Duty Cycle for Gate Drivers
#define APP_SETTINGS_PWM_GATE_DRV_DEF_DUTY_CYCLE				32767	// 50%

//*****************************************************************************
//
// PWM BSP parameters.
//
//*****************************************************************************

// Frequency and period of PWM source clock
#define BSP_SETTINGS_PWM_PLL_CLOCK_DIV					1
#define BSP_SETTINGS_PWM_PLL_CLOCK_FREQ					((FRCFREQ * 16) / BSP_SETTINGS_PWM_PLL_CLOCK_DIV)			// ((7372800Hz * 16) / 1) = 117964800Hz
#define BSP_SETTINGS_PWM_CLOCK_PERIOD					(1000000000000LL / (BSP_SETTINGS_PWM_PLL_CLOCK_FREQ * 8))	// 1060ps (1000000000000/943718400Hz) instead of 1041ps (1000000000000/961000000Hz)

// PWM Channels mapping to Master Time Base (Primary or Secondary)
#if (!defined PINS28_STARTER_BOARD)
// Inresol Inverter
// Engineering Sample Evaluation Board
#define BSP_PWM_CHANNEL_1_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_PRIMARY
#define BSP_PWM_CHANNEL_2_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_PRIMARY
#define BSP_PWM_CHANNEL_3_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_PRIMARY
#define BSP_PWM_CHANNEL_4_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_SECONDARY
#define BSP_PWM_CHANNEL_5_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_PRIMARY
#else
// 28-pins Starter Board
#define BSP_PWM_CHANNEL_1_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_PRIMARY
#define BSP_PWM_CHANNEL_2_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_PRIMARY
#define BSP_PWM_CHANNEL_3_MASTER_TIME_BASE_SELECT		BSP_PWM_MASTER_TIME_BASE_SECONDARY
#define BSP_PWM_CHANNEL_4_MASTER_TIME_BASE_SELECT		0
#define BSP_PWM_CHANNEL_5_MASTER_TIME_BASE_SELECT		0
#endif

// PWM Channels mapping to Dead Times for IGBTs and Gate Drivers (Rising Edge & Falling Edge)
#if (!defined PINS28_STARTER_BOARD)
// Inresol Inverter
// Engineering Sample Evaluation Board
#define BSP_PWM_CHANNEL_1_DEF_DEAD_TIME_RISING_EDGE		APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_1_DEF_DEAD_TIME_FALLING_EDGE	APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_2_DEF_DEAD_TIME_RISING_EDGE		APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_2_DEF_DEAD_TIME_FALLING_EDGE	APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_3_DEF_DEAD_TIME_RISING_EDGE		APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_3_DEF_DEAD_TIME_FALLING_EDGE	APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_4_DEF_DEAD_TIME_RISING_EDGE		APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_4_DEF_DEAD_TIME_FALLING_EDGE	APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_5_DEF_DEAD_TIME_RISING_EDGE		0
#define BSP_PWM_CHANNEL_5_DEF_DEAD_TIME_FALLING_EDGE	0
#else
// 28-pins Starter Board
#define BSP_PWM_CHANNEL_1_DEF_DEAD_TIME_RISING_EDGE		APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_1_DEF_DEAD_TIME_FALLING_EDGE	APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_2_DEF_DEAD_TIME_RISING_EDGE		APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_2_DEF_DEAD_TIME_FALLING_EDGE	APP_SETTINGS_PWM_IGBT_DEF_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_3_DEF_DEAD_TIME_RISING_EDGE		APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_3_DEF_DEAD_TIME_FALLING_EDGE	APP_SETTINGS_PWM_GATE_DRV_DEF_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_4_DEF_DEAD_TIME_RISING_EDGE		0
#define BSP_PWM_CHANNEL_4_DEF_DEAD_TIME_FALLING_EDGE	0
#endif

#if (!defined PINS28_STARTER_BOARD)
// Inresol Inverter
// Engineering Sample Evaluation Board
#define BSP_PWM_CHANNEL_1_MIN_DEAD_TIME_RISING_EDGE		BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_1_MIN_DEAD_TIME_FALLING_EDGE	BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_2_MIN_DEAD_TIME_RISING_EDGE		BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_2_MIN_DEAD_TIME_FALLING_EDGE	BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_3_MIN_DEAD_TIME_RISING_EDGE		BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_3_MIN_DEAD_TIME_FALLING_EDGE	BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_4_MIN_DEAD_TIME_RISING_EDGE		BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_4_MIN_DEAD_TIME_FALLING_EDGE	BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_5_MIN_DEAD_TIME_RISING_EDGE		0
#define BSP_PWM_CHANNEL_5_MIN_DEAD_TIME_FALLING_EDGE	0
#else
// 28-pins Starter Board
#define BSP_PWM_CHANNEL_1_MIN_DEAD_TIME_RISING_EDGE		BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_1_MIN_DEAD_TIME_FALLING_EDGE	BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_2_MIN_DEAD_TIME_RISING_EDGE		BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_2_MIN_DEAD_TIME_FALLING_EDGE	BSP_SETTINGS_PWM_IGBT_MIN_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_3_MIN_DEAD_TIME_RISING_EDGE		BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_RISING_EDGE
#define BSP_PWM_CHANNEL_3_MIN_DEAD_TIME_FALLING_EDGE	BSP_SETTINGS_PWM_GATE_DRV_MIN_DEAD_TIME_FALLING_EDGE
#define BSP_PWM_CHANNEL_4_MIN_DEAD_TIME_RISING_EDGE		0
#define BSP_PWM_CHANNEL_4_MIN_DEAD_TIME_FALLING_EDGE	0
#define BSP_PWM_CHANNEL_5_MIN_DEAD_TIME_RISING_EDGE		0
#define BSP_PWM_CHANNEL_5_MIN_DEAD_TIME_FALLING_EDGE	0
#endif

// PWM Interrupt Channel, Handler, Level
#define BSP_PWM_INTERRUPT_CHANNEL						BSP_PWM_CHANNEL_NUMBER_2
#define BSP_PWM_INTERRUPT_HANDLER()						_PWM2Interrupt()
#define BSP_PWM_INTERRUPT_CALLBACK()					App_PWM_Process_IRQ()
#define BSP_PWM_INTERRUPT_LEVEL							4
#define BSP_PWM_INTERRUPT_CLEAR()						BSP_PWM_Channel_2_Interrupt_Clear()

//*****************************************************************************
//
// PWM App parameters.
//
//*****************************************************************************

// Clock Dividers for Master Time Base (Primary and Secondary)
#define BSP_SETTINGS_PWM_TIME_BASE_PRIMARY_DIV			2
#define BSP_SETTINGS_PWM_TIME_BASE_SECONDARY_DIV		2

// Clock Divider for Trigger
#define BSP_SETTINGS_PWM_TRIGGER_DIV					8

// Switching Frequency for IGBTs and Gate Drivers
//#define APP_SETTINGS_PWM_IGBT_SW_FREQ					400000		// 400 kHz
//#define APP_SETTINGS_PWM_IGBT_SW_FREQ					200000		// 200 kHz
//#define APP_SETTINGS_PWM_IGBT_SW_FREQ					64000		// 64 kHz
//#define APP_SETTINGS_PWM_IGBT_SW_FREQ					32000		// 32 kHz
#define APP_SETTINGS_PWM_IGBT_SW_FREQ					16000		// 16 kHz
#define APP_SETTINGS_PWM_GATE_DRV_SW_FREQ				250000		// 250 kHz

#define APP_SETTINGS_PWM_DELAYS_ENABLED
// 100ms Delay before 250kHz Gate-Driver PWM Oscillator Start
#define APP_SETTINGS_PWM_DELAY_BEFORE_GATE_DRV			100			// 100ms
// 100ms Delay before 16kHz IGBTs PWM Start
#define APP_SETTINGS_PWM_DELAY_BEFORE_IGBTS				100			// 100ms

#define BSP_SETTINGS_PWM_MARGIN							0			// From 0 to 2

#ifndef ADC_TIME_SHIFT_ENABLED										// Enable time shift between conversion of ADC Dedicated and Shared cores
//#define APP_SETTINGS_PWM_PRIMARY_TRIGGER_DELAY		1200		// 1.2us
//#define APP_SETTINGS_PWM_SECONDARY_TRIGGER_DELAY		5000		// 5.0us
#define APP_SETTINGS_PWM_PRIMARY_TRIGGER_DELAY			1200		// 1.2us
#define APP_SETTINGS_PWM_SECONDARY_TRIGGER_DELAY		30000		// 30.0us
#else	// ADC_TIME_SHIFT_ENABLED
#define APP_SETTINGS_PWM_PRIMARY_TRIGGER_DELAY_ADC_S	1200		// 1.2us
#define APP_SETTINGS_PWM_SECONDARY_TRIGGER_DELAY_ADC_S	29500		// 29.5us
#define APP_SETTINGS_PWM_PRIMARY_TRIGGER_DELAY_ADC_D	2200		// 2.2us
#define APP_SETTINGS_PWM_SECONDARY_TRIGGER_DELAY_ADC_D	30500		// 30.5us
#endif	// ADC_TIME_SHIFT_ENABLED

#if 0
#define PWM_TST1_SET()	GPIO_TST1_SET()
#define PWM_TST1_CLR()	GPIO_TST1_CLR()
#define PWM_TST1_TGL()	GPIO_TST1_TGL()
#define PWM_TST2_SET()	GPIO_TST2_SET()
#define PWM_TST2_CLR()	GPIO_TST2_CLR()
#define PWM_TST2_TGL()	GPIO_TST2_TGL()
#define PWM_TST3_SET()	GPIO_TST3_SET()
#define PWM_TST3_CLR()	GPIO_TST3_CLR()
#define PWM_TST3_TGL()	GPIO_TST3_TGL()
#else
#define PWM_TST1_SET()
#define PWM_TST1_CLR()
#define PWM_TST1_TGL()
#define PWM_TST2_SET()
#define PWM_TST2_CLR()
#define PWM_TST2_TGL()
#define PWM_TST3_SET()
#define PWM_TST3_CLR()
#define PWM_TST3_TGL()
#endif

#endif	// CONFIG_PWM_H
