#
#Mon Feb 13 16:28:12 CET 2017
USUAL.languagetoolchain.dir=C\:\\Program Files (x86)\\Microchip\\xc32\\v1.33\\bin
USUAL.languagetoolchain.version=1.33
conf.ids=USUAL,BOOTAPP
USUAL.com-microchip-mplab-nbide-toolchainXC32-XC32LanguageToolchain.md5=1a156f99533b5b45dd73f985cd47ba37
configurations-xml=2d8d0db425fa4b166d8e0e96fd5b4723
BOOTAPP.languagetoolchain.version=1.33
com-microchip-mplab-nbide-embedded-makeproject-MakeProject.md5=8b140fb87818dc96ed4f726b716b40e9
BOOTAPP.com-microchip-mplab-nbide-toolchainXC32-XC32LanguageToolchain.md5=1a156f99533b5b45dd73f985cd47ba37
host.platform=windows
BOOTAPP.languagetoolchain.dir=C\:\\Program Files (x86)\\Microchip\\xc32\\v1.33\\bin
