#ifndef _PINS_H
#define _PINS_H

#define ADC_AN0_CHAN           0
#define ADC_AN1_CHAN           1
#define ADC_AN2_CHAN           2
#define ADC_AN3_CHAN           3
#define ADC_AN4_CHAN           4
#define ADC_AN5_CHAN           8
#define ADC_AN6_CHAN           6
#define ADC_AN7_CHAN           7
#define ADC_TOUCH1_CHAN        9
#define ADC_TOUCH2_CHAN        10
#define ADC_TOUCH3_CHAN        11
#define ADC_TOUCH4_CHAN        5

#define BUS_CTRL_IN            PORTB
#define BUS_CTRL_OUT           LATB
#define BUS_CTRL_TRIS          TRISB
#define BUS_CTRL_MASK          0x1E
#define BUS_IDENT_IN           (PORTBbits.RB0)
#define BUS_IDENT_MASK         0x01
#define BUS_IDENT_BIT          0
#define BUS_ATN_IN             (PORTBbits.RB3)
#define BUS_ATN_MASK           0x08
#define BUS_ATN_BIT            1
#define BUS_ACK_MASK           0x12
#define BUS_ACK1_IN            (PORTBbits.RB4)
#define BUS_ACK1_OUT           (LATBbits.LATB4)
#define BUS_ACK1_TRIS          (TRISBbits.TRISB4)
#define BUS_ACK1_MASK          0x10
#define BUS_ACK1_BIT           4
#define BUS_ACK2_IN            (PORTBbits.RB1)
#define BUS_ACK2_OUT           (LATBbits.LATB1)
#define BUS_ACK2_TRIS          (TRISBbits.TRISB1)
#define BUS_ACK2_MASK          0x02
#define BUS_ACK2_BIT           1
#define BUS_CLK_IN             (PORTBbits.RB2)
#define BUS_CLK_MASK           0x04
#define BUS_CLK_BIT            2
#define BUS_DATA_IN            PORTG
#define BUS_DATA_OUT           LATG
#define BUS_DATA_TRIS          TRISG
#define BUS_DATA_MASK          0x0F
#define BUS_DATA_BIT           0
#define BUS_DATA0_MASK         0x01
#define BUS_DATA0_BIT          0
#define BUS_DATA1_MASK         0x02
#define BUS_DATA1_BIT          1
#define BUS_DATA2_MASK         0x04
#define BUS_DATA2_BIT          2
#define BUS_DATA3_MASK         0x08
#define BUS_DATA3_BIT          3

#define EFLASH_CTRL            LATC
#define EFLASH_CS              (LATCbits.LATC2)
#define EFLASH_CS_MASK         0x04
#define EFLASH_CS_BIT          2
#define EFLASH_CLOCK           (LATCbits.LATC3)
#define EFLASH_CLOCK_MASK      0x08
#define EFLASH_CLOCK_BIT       3
#define EFLASH_MISO            (PORTCbits.RC4)
#define EFLASH_MISO_MASK       0x10
#define EFLASH_MISO_BIT        4
#define EFLASH_MOSI            (LATCbits.LATC5)
#define EFLASH_MOSI_MASK       0x20
#define EFLASH_MOSI_BIT        5
#define EFLASH_RESET           (LATEbits.LATE5)
#define EFLASH_RESET_MASK      0x20
#define EFLASH_RESET_BIT       5
#define EFLASH_CMD_ARRAY_READ  0x03
#define EFLASH_CMD_SPECIAL     0x3D
#define EFLASH_CMD_REWRITE1    0x83
#define EFLASH_CMD_FILL1       0x84
#define EFLASH_CMD_REWRITE2    0x86
#define EFLASH_CMD_FILL2       0x87
#define EFLASH_CMD_POWERUP     0xAB
#define EFLASH_CMD_POWERDOWN   0xB9
#define EFLASH_CMD_STATUS      0xD7

#define EPFLASH_CTRL           LATC
#define EPFLASH_DATA           PORTD
#define EPFLASH_TRIS           TRISD
#define EPFLASH_TRIS_READ      0xFF
#define EPFLASH_TRIS_WRITE     0x00
#define EPFLASH_RB             (PORTCbits.RC0)
#define EPFLASH_RB_MASK        0x01
#define EPFLASH_RB_BIT         0
#define EPFLASH_RB_PORT        PORTC
#define EPFLASH_WE             (LATCbits.LATC1)
#define EPFLASH_WE_MASK        0x02
#define EPFLASH_WE_BIT         1
#define EPFLASH_WE_PORT        LATC
#define EPFLASH_ALE            (LATCbits.LATC3)
#define EPFLASH_ALE_MASK       0x08
#define EPFLASH_ALE_BIT        3
#define EPFLASH_ALE_PORT       LATC
#define EPFLASH_CLE            (LATCbits.LATC4)
#define EPFLASH_CLE_MASK       0x10
#define EPFLASH_CLE_BIT        4
#define EPFLASH_CKE_PORT       LATC
#define EPFLASH_CE             (LATCbits.LATC5)
#define EPFLASH_CE_MASK        0x20
#define EPFLASH_CE_BIT         5
#define EPFLASH_CE_PORT        LATC
#define EPFLASH_RE             (LATEbits.LATE5)
#define EPFLASH_RE_MASK        0x20
#define EPFLASH_RE_BIT         5
#define EPFLASH_RE_PORT        LATE

#define DISP_CTRL              LATE
#define DISP_DATA              PORTD
#define DISP_TRIS              TRISD
#define DISP_DC                (LATEbits.LATE0)
#define DISP_DC_BIT            0
#define DISP_DC_MASK           0x01
#define DISP_RD                (LATEbits.LATE1)
#define DISP_RD_MASK           0x02
#define DISP_RD_BIT            1
#define DISP_CS                (LATEbits.LATE4)
#define DISP_CS_MASK           0x10
#define DISP_CS_BIT            4
#define DISP_WR                (LATEbits.LATE6)
#define DISP_WR_MASK           0x40
#define DISP_WR_BIT            6
#define DISP_LED               (LATEbits.LATE7)
#define DISP_LED_MASK          0x80
#define DISP_LED_BIT           7
#define DISP_RESET             (LATAbits.LATA3)
#define DISP_R00_DRV_CODE      0x00
#define DISP_R00_OSC_START     0x00
#define DISP_R01_DRV_OUT_CTRL  0x01
#define DISP_R02_DRV_LCD_CTRL  0x02
#define DISP_R03_PWR_CTRL1     0x03
#define DISP_R07_DISPLAY_CTRL  0x07
#define DISP_R0B_FRAME_CYCLE   0x0B
#define DISP_R0C_PWR_CTRL2     0x0C
#define DISP_R0D_PWR_CTRL3     0x0D
#define DISP_R0E_PWR_CTRL4     0x0E
#define DISP_R0F_GATE_SCAN     0x0F
#define DISP_R10_SLEEP_MODE    0x10
#define DISP_R11_ENTRY_MODE    0x11
#define DISP_R15_GEN_IF_CTRL   0x15
#define DISP_R1E_PWR_CTRL5     0x1e
#define DISP_R22_RAM_PORT      0x22
#define DISP_R25_FRAME_FREQ    0x25
#define DISP_R26_ANALOG_CTRL   0x26
#define DISP_R27_UNKNOWN       0x27
#define DISP_R28_VCOM_OTP1     0x28
#define DISP_R29_VCOM_OTP2     0x29
#define DISP_R30_GAMMA1        0x30
#define DISP_R31_GAMMA2        0x31
#define DISP_R32_GAMMA3        0x32
#define DISP_R33_GAMMA4        0x33
#define DISP_R34_GAMMA5        0x34
#define DISP_R35_GAMMA6        0x35
#define DISP_R36_GAMMA7        0x36
#define DISP_R37_GAMMA8        0x37
#define DISP_R3A_GAMMA9        0x3A
#define DISP_R3B_GAMMA10       0x3B
#define DISP_R41_VSCROLL1      0x41
#define DISP_R42_VSCROLL2      0x42
#define DISP_R44_VRAM_POS      0x44
#define DISP_R45_HRAM_START    0x45
#define DISP_R46_HRAM_END      0x46
#define DISP_R48_SCREEN1_START 0x48
#define DISP_R49_SCREEN1_END   0x49
#define DISP_R4A_SCREEN2_START 0x4A
#define DISP_R4B_SCREEN2_END   0x4B
#define DISP_R4E_XRAM_ADDR     0x4E
#define DISP_R4F_YRAM_ADDR     0x4F

#define LED_CTRL_IN            PORTF
#define LED_CTRL_OUT           LATF
#define LED_MODE               (LATFbits.LATF5)
#define LED_MODE_MASK          0x20
#define LED_MODE_BIT           5
#define LED_SIN                (LATFbits.LATF4)
#define LED_SIN_MASK           0x10
#define LED_SIN_BIT            4
#define LED_SCLK               (LATFbits.LATF3)
#define LED_SCLK_MASK          0x08
#define LED_SCLK_BIT           3
#define LED_XLAT               (LATFbits.LATF2)
#define LED_XLAT_MASK          0x04
#define LED_XLAT_BIT           2
#define LED_BLANK              (LATFbits.LATF1)
#define LED_BLANK_MASK         0x02
#define LED_BLANK_BIT          1

#define SWITCH_1_PIN           (PORTAbits.RA0)
#define SWITCH_2_PIN           (PORTAbits.RA1)
#define SWITCH_3_PIN           (PORTAbits.RA4)
#define SWITCH_4_PIN           (PORTAbits.RA5)
#define SWITCH_ON_PIN          (PORTFbits.RF7)
#define SWITCH_OFF_PIN         (PORTFbits.RF6)

#endif